-- GENERATED by scripts/mt/build-rollback.py — do not edit by hand.
-- Rollback of migrations/0042_organizations.sql — ALL of it — to the exact schema the database had before
-- it: 0036, with 0041 applied (canopy-multitenancy.md §3.5). What was added last is undone first:
-- sections 10–5 (the org's image, the invite's mail columns, the abuse counters, the identity uid, the
-- platform tables, the superadmin), then 4–1 (search, the rebuilt tables, the added columns, the org
-- tables). ONE transaction: it either completes or changes nothing.
--
-- NOT undone:
--   • 0041_trov_name.sql — its own migration, applied before this one: the default sender stays
--     `Trov <hello@trov.dev>` and 0041 stays recorded in d1_migrations.
--   • nothing else. Unlike a rollback of ten separate files, no added column may be left behind, however
--     harmless (`identities.provider_uid`, `persons.org_limit`, …): this file also removes the migration
--     from d1_migrations, and the next `migrations apply` would fail on a column that still exists.
-- LOST with it (there is nowhere in the old schema to keep them): every org, membership, invite,
-- repository / environment row, integration secret and audit row; usage and abuse counters; the GitHub
-- account ids pinned at sign-in (re-pinned at the next one); org images' columns (the bytes stay in R2).
-- It keeps ONLY the 'org_saplinglearn' rows of every tenant table, so it REFUSES to run once any other org
-- exists (the guard below) — and on a database the migration never ran on (there is no `orgs`). Apply with
--   wrangler d1 execute trov --remote --file scripts/mt/rollback/0042_organizations.down.sql
-- together with `wrangler rollback` to the pre-migration Worker. Prefer D1 Time Travel when in its window.

PRAGMA defer_foreign_keys = true;

-- Refuse when another org exists: its rows would be deleted.
CREATE TABLE _mt_down_guard (other_orgs INTEGER NOT NULL CHECK (other_orgs = 0));
INSERT INTO _mt_down_guard (other_orgs) SELECT COUNT(*) FROM orgs WHERE id <> 'org_saplinglearn';
DROP TABLE _mt_down_guard;

-- ── 1. sections 10–5: the later additions ──
-- (Sections 10, 9 and 6's columns sit on `orgs` / `org_invites`, which step 5 drops whole.)
DROP INDEX IF EXISTS idx_abuse_counters_bucket;
DROP INDEX IF EXISTS idx_org_admin_audit_org;
DROP INDEX IF EXISTS idx_org_admin_audit_at;
DROP INDEX IF EXISTS idx_org_usage_daily_day;
DROP TABLE IF EXISTS abuse_counters;
DROP TABLE IF EXISTS org_admin_audit;
DROP TABLE IF EXISTS org_usage_daily;
DROP TABLE IF EXISTS platform_admins;
ALTER TABLE identities DROP COLUMN provider_uid;

-- ── 2. every trigger the migration created (they reference org_id) ──
DROP TRIGGER IF EXISTS docs_fts_ai;
DROP TRIGGER IF EXISTS docs_fts_au;
DROP TRIGGER IF EXISTS docs_fts_ad;
DROP TRIGGER IF EXISTS feed_fts_ai;
DROP TRIGGER IF EXISTS feed_fts_ad;
DROP TRIGGER IF EXISTS adrs_fts_ai;
DROP TRIGGER IF EXISTS adrs_fts_ad;
DROP TRIGGER IF EXISTS roadmap_fts_plan_au;
DROP TRIGGER IF EXISTS roadmap_fts_sprint_ai;
DROP TRIGGER IF EXISTS roadmap_fts_sprint_au;
DROP TRIGGER IF EXISTS roadmap_fts_sprint_ad;
DROP TRIGGER IF EXISTS tickets_fts_ai;
DROP TRIGGER IF EXISTS tickets_fts_au;
DROP TRIGGER IF EXISTS tickets_fts_ad;
DROP TRIGGER IF EXISTS prompts_fts_ai;
DROP TRIGGER IF EXISTS prompts_fts_au;
DROP TRIGGER IF EXISTS prompts_fts_ad;
DROP TRIGGER IF EXISTS prompts_fts_vai;
DROP TRIGGER IF EXISTS prompts_fts_vau;
DROP TRIGGER IF EXISTS artifacts_fts_ad;
DROP TRIGGER IF EXISTS tickets_number_ai;
DROP TRIGGER IF EXISTS handoffs_number_ai;

-- ── 3. the tables that only GAINED org_id (and number): drop the indexes on it, then the columns ──
DROP INDEX IF EXISTS idx_sprints_org_id;
DROP INDEX IF EXISTS idx_tickets_org_id;
DROP INDEX IF EXISTS idx_tickets_source_ref;
DROP INDEX IF EXISTS idx_tickets_org_number;
DROP INDEX IF EXISTS idx_handoffs_org_number;
DROP INDEX IF EXISTS idx_adrs_hash_org;
DELETE FROM feed WHERE org_id <> 'org_saplinglearn';
DELETE FROM adrs WHERE org_id <> 'org_saplinglearn';
DELETE FROM needs_triage WHERE org_id <> 'org_saplinglearn';
DELETE FROM sprints WHERE org_id <> 'org_saplinglearn';
DELETE FROM sprint_resources WHERE org_id <> 'org_saplinglearn';
DELETE FROM sprint_progress WHERE org_id <> 'org_saplinglearn';
DELETE FROM tickets WHERE org_id <> 'org_saplinglearn';
DELETE FROM ticket_assignees WHERE org_id <> 'org_saplinglearn';
DELETE FROM ticket_links WHERE org_id <> 'org_saplinglearn';
DELETE FROM ticket_comments WHERE org_id <> 'org_saplinglearn';
DELETE FROM ticket_events WHERE org_id <> 'org_saplinglearn';
DELETE FROM handoffs WHERE org_id <> 'org_saplinglearn';
DELETE FROM mcp_tokens WHERE org_id <> 'org_saplinglearn';
DELETE FROM oauth_grants WHERE org_id <> 'org_saplinglearn';
DELETE FROM oauth_codes WHERE org_id <> 'org_saplinglearn';
DELETE FROM artifact_versions WHERE org_id <> 'org_saplinglearn';
DELETE FROM artifact_links WHERE org_id <> 'org_saplinglearn';
DELETE FROM artifact_upload_tokens WHERE org_id <> 'org_saplinglearn';
DELETE FROM doc_image_upload_tokens WHERE org_id <> 'org_saplinglearn';
DELETE FROM notification_outbox WHERE org_id <> 'org_saplinglearn';
DELETE FROM notification_outbox_bodies WHERE org_id <> 'org_saplinglearn';
ALTER TABLE feed DROP COLUMN org_id;
ALTER TABLE adrs DROP COLUMN org_id;
ALTER TABLE needs_triage DROP COLUMN org_id;
ALTER TABLE sprints DROP COLUMN org_id;
ALTER TABLE sprint_resources DROP COLUMN org_id;
ALTER TABLE sprint_progress DROP COLUMN org_id;
ALTER TABLE tickets DROP COLUMN org_id;
ALTER TABLE ticket_assignees DROP COLUMN org_id;
ALTER TABLE ticket_links DROP COLUMN org_id;
ALTER TABLE ticket_comments DROP COLUMN org_id;
ALTER TABLE ticket_events DROP COLUMN org_id;
ALTER TABLE handoffs DROP COLUMN org_id;
ALTER TABLE mcp_tokens DROP COLUMN org_id;
ALTER TABLE oauth_grants DROP COLUMN org_id;
ALTER TABLE oauth_codes DROP COLUMN org_id;
ALTER TABLE artifact_versions DROP COLUMN org_id;
ALTER TABLE artifact_links DROP COLUMN org_id;
ALTER TABLE artifact_upload_tokens DROP COLUMN org_id;
ALTER TABLE doc_image_upload_tokens DROP COLUMN org_id;
ALTER TABLE notification_outbox DROP COLUMN org_id;
ALTER TABLE notification_outbox_bodies DROP COLUMN org_id;
ALTER TABLE tickets DROP COLUMN number;
ALTER TABLE handoffs DROP COLUMN number;
CREATE UNIQUE INDEX idx_tickets_source_ref ON tickets(source_ref) WHERE source_ref IS NOT NULL;

-- ── 4. the rebuilt tables, back to their 0036 definitions ──
CREATE TABLE docs_old (
  slug TEXT PRIMARY KEY,
  section TEXT NOT NULL REFERENCES sections(name),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  current_version INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT,
  updated_by TEXT
, space TEXT NOT NULL DEFAULT 'canopy', owner TEXT);
INSERT INTO docs_old (slug, section, title, body, current_version, updated_at, updated_by, space, owner) SELECT slug, section, title, body, current_version, updated_at, updated_by, space, owner FROM docs WHERE org_id = 'org_saplinglearn';
CREATE TABLE doc_versions_old (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL REFERENCES docs_old(slug),
  version INTEGER NOT NULL,
  body TEXT NOT NULL,
  summary TEXT,
  status TEXT NOT NULL DEFAULT 'staged',
  confidence TEXT,
  created_at TEXT NOT NULL,
  created_by TEXT NOT NULL
, content_hash   TEXT, base_version   INTEGER, change_kind    TEXT, low_confidence INTEGER NOT NULL DEFAULT 0);
INSERT INTO doc_versions_old (id, slug, version, body, summary, status, confidence, created_at, created_by, content_hash, base_version, change_kind, low_confidence) SELECT id, slug, version, body, summary, status, confidence, created_at, created_by, content_hash, base_version, change_kind, low_confidence FROM doc_versions WHERE org_id = 'org_saplinglearn';
INSERT INTO sqlite_sequence (name, seq) SELECT 'doc_versions_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'doc_versions_old');
UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = 'doc_versions'), 0)) WHERE name = 'doc_versions_old';
CREATE TABLE entry_tags_old (
  tag TEXT NOT NULL REFERENCES tags(tag),
  entry_type TEXT NOT NULL,
  entry_id TEXT NOT NULL,
  PRIMARY KEY (tag, entry_type, entry_id)
);
INSERT INTO entry_tags_old (tag, entry_type, entry_id) SELECT tag, entry_type, entry_id FROM entry_tags WHERE org_id = 'org_saplinglearn';
CREATE TABLE processed_items_old (
  session_id TEXT NOT NULL,
  item_index INTEGER NOT NULL,
  item_type  TEXT NOT NULL,      -- feed | doc | adr | milestone | focus | triage
  outcome    TEXT NOT NULL,      -- the gate's verdict (written | staged | triaged | unchanged)
  ref        TEXT,               -- what it became (e.g. "slug@2", a feed/adr id), for transparency
  created_at TEXT NOT NULL,
  PRIMARY KEY (session_id, item_index)
);
INSERT INTO processed_items_old (session_id, item_index, item_type, outcome, ref, created_at) SELECT session_id, item_index, item_type, outcome, ref, created_at FROM processed_items WHERE org_id = 'org_saplinglearn';
CREATE TABLE events_old (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  semantic_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,            -- 'pr_merged' | 'pr_closed' | 'issue'
  ref_number INTEGER NOT NULL,         -- the PR/issue number (grouping key)
  subject_login TEXT NOT NULL,         -- whose work this is; trusted post-HMAC
  raw TEXT NOT NULL,                   -- JSON snapshot slice — the source of truth
  provenance TEXT NOT NULL,            -- 'webhook' | 'backfill'
  occurred_at TEXT,                    -- from the payload (ISO8601)
  recorded_at TEXT NOT NULL,
  recorded_by TEXT NOT NULL            -- writer identity (the authenticated principal)
);
INSERT INTO events_old (id, semantic_key, event_type, ref_number, subject_login, raw, provenance, occurred_at, recorded_at, recorded_by) SELECT id, semantic_key, event_type, ref_number, subject_login, raw, provenance, occurred_at, recorded_at, recorded_by FROM events WHERE org_id = 'org_saplinglearn';
INSERT INTO sqlite_sequence (name, seq) SELECT 'events_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'events_old');
UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = 'events'), 0)) WHERE name = 'events_old';
CREATE TABLE pr_summaries_old (
  semantic_key TEXT PRIMARY KEY REFERENCES events_old(semantic_key),
  pr_number INTEGER NOT NULL,
  model TEXT,                          -- generator id, or 'excerpt' for the deterministic fallback
  created_at TEXT NOT NULL
, title TEXT, what TEXT, why TEXT, impact TEXT);
INSERT INTO pr_summaries_old (semantic_key, pr_number, model, created_at, title, what, why, impact) SELECT semantic_key, pr_number, model, created_at, title, what, why, impact FROM pr_summaries WHERE org_id = 'org_saplinglearn';
CREATE TABLE issue_summaries_old (
  issue_number INTEGER PRIMARY KEY,
  summary TEXT NOT NULL,
  model TEXT,                          -- generator id, or 'excerpt' for the deterministic fallback
  created_at TEXT NOT NULL
, title TEXT, next_step TEXT);
INSERT INTO issue_summaries_old (issue_number, summary, model, created_at, title, next_step) SELECT issue_number, summary, model, created_at, title, next_step FROM issue_summaries WHERE org_id = 'org_saplinglearn';
CREATE TABLE plan_old (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  narrative TEXT NOT NULL DEFAULT '',
  current_version INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT,
  updated_by TEXT
);
INSERT INTO plan_old (id, narrative, current_version, updated_at, updated_by) SELECT 1, narrative, current_version, updated_at, updated_by FROM plan WHERE org_id = 'org_saplinglearn';
CREATE TABLE plan_versions_old (
  version INTEGER PRIMARY KEY,
  narrative TEXT NOT NULL,
  sprints_json TEXT NOT NULL,       -- full milestones snapshot AFTER this write
  created_at TEXT NOT NULL,
  created_by TEXT NOT NULL
);
INSERT INTO plan_versions_old (version, narrative, sprints_json, created_at, created_by) SELECT version, narrative, sprints_json, created_at, created_by FROM plan_versions WHERE org_id = 'org_saplinglearn';
CREATE TABLE identity_tasks_old (
  login TEXT PRIMARY KEY,                   -- the unmapped GitHub login
  first_seen TEXT NOT NULL,                 -- ISO8601 of the first event that raised it
  status TEXT NOT NULL DEFAULT 'pending',   -- 'pending' | 'resolved'
  resolved_at TEXT,                         -- ISO8601 when mapped
  resolved_by TEXT                          -- the authenticated principal who mapped it
);
INSERT INTO identity_tasks_old (login, first_seen, status, resolved_at, resolved_by) SELECT login, first_seen, status, resolved_at, resolved_by FROM identity_tasks WHERE org_id = 'org_saplinglearn';
CREATE TABLE notification_policy_old (
  kind TEXT PRIMARY KEY,
  default_cadence TEXT NOT NULL CHECK (default_cadence IN ('daily','weekly','off')),
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  updated_by TEXT NOT NULL
);
INSERT INTO notification_policy_old (kind, default_cadence, enabled, updated_at, updated_by) SELECT kind, default_cadence, enabled, updated_at, updated_by FROM notification_policy WHERE org_id = 'org_saplinglearn';
CREATE TABLE notification_settings_old (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  send_hour INTEGER NOT NULL DEFAULT 8,
  timezone TEXT NOT NULL DEFAULT 'America/New_York',
  from_address TEXT NOT NULL
);
INSERT INTO notification_settings_old (id, send_hour, timezone, from_address) SELECT 1, send_hour, timezone, from_address FROM notification_settings WHERE org_id = 'org_saplinglearn';
CREATE TABLE notification_prefs_old (
  user_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  cadence TEXT NOT NULL CHECK (cadence IN ('daily','weekly','off')),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (user_id, kind)
);
INSERT INTO notification_prefs_old (user_id, kind, cadence, updated_at) SELECT user_id, kind, cadence, updated_at FROM notification_prefs WHERE org_id = 'org_saplinglearn';
CREATE TABLE repo_events_old (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  semantic_key TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL CHECK (kind IN ('push','pr','review','deploy','check','run')),
  ref TEXT,
  sha TEXT,
  number INTEGER,
  env TEXT,
  part TEXT CHECK (part IS NULL OR part IN ('backend','frontend')),
  state TEXT,
  name TEXT,
  actor_login TEXT,
  title TEXT,
  url TEXT,
  count INTEGER,
  raw TEXT NOT NULL,
  provenance TEXT NOT NULL CHECK (provenance IN ('webhook','backfill')),
  occurred_at TEXT NOT NULL,
  recorded_at TEXT NOT NULL
);
INSERT INTO repo_events_old (id, semantic_key, kind, ref, sha, number, env, part, state, name, actor_login, title, url, count, raw, provenance, occurred_at, recorded_at) SELECT id, semantic_key, kind, ref, sha, number, env, part, state, name, actor_login, title, url, count, raw, provenance, occurred_at, recorded_at FROM repo_events WHERE org_id = 'org_saplinglearn';
INSERT INTO sqlite_sequence (name, seq) SELECT 'repo_events_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'repo_events_old');
UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = 'repo_events'), 0)) WHERE name = 'repo_events_old';
CREATE TABLE repo_snapshots_old (
  kind TEXT PRIMARY KEY,
  json TEXT NOT NULL,
  computed_at TEXT NOT NULL
);
INSERT INTO repo_snapshots_old (kind, json, computed_at) SELECT kind, json, computed_at FROM repo_snapshots WHERE org_id = 'org_saplinglearn';
CREATE TABLE repo_metrics_old (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  metric TEXT NOT NULL,
  env TEXT NOT NULL DEFAULT '',
  part TEXT NOT NULL DEFAULT '',
  value REAL NOT NULL,
  at TEXT NOT NULL,
  UNIQUE (metric, env, part, at)
);
INSERT INTO repo_metrics_old (id, metric, env, part, value, at) SELECT id, metric, env, part, value, at FROM repo_metrics WHERE org_id = 'org_saplinglearn';
INSERT INTO sqlite_sequence (name, seq) SELECT 'repo_metrics_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'repo_metrics_old');
UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = 'repo_metrics'), 0)) WHERE name = 'repo_metrics_old';
CREATE TABLE prompts_old (
  slug TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  tags TEXT NOT NULL DEFAULT '[]',          -- JSON array, lowercased, deduped
  author TEXT NOT NULL,                     -- the creator
  current_version INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, use_count INTEGER NOT NULL DEFAULT 0, last_used_at TEXT, deleted_at TEXT, deleted_by TEXT);
INSERT INTO prompts_old (slug, title, description, tags, author, current_version, created_at, updated_at, use_count, last_used_at, deleted_at, deleted_by) SELECT slug, title, description, tags, author, current_version, created_at, updated_at, use_count, last_used_at, deleted_at, deleted_by FROM prompts WHERE org_id = 'org_saplinglearn';
CREATE TABLE prompt_versions_old (
  slug TEXT NOT NULL,
  version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('draft','staged','published')),
  author TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (slug, version)
);
INSERT INTO prompt_versions_old (slug, version, status, author, summary, body, created_at) SELECT slug, version, status, author, summary, body, created_at FROM prompt_versions WHERE org_id = 'org_saplinglearn';
CREATE TABLE artifact_pages_old (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE CHECK (length(slug) BETWEEN 1 AND 60),
  title TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('html','markdown','svg','mermaid','image','pdf','file')),
  area TEXT NOT NULL CHECK (area IN ('auth','architecture','infra','api','ui','data')),
  repo TEXT NOT NULL DEFAULT '',                 -- "owner/repo" or ''
  author_id TEXT NOT NULL,                       -- a person handle
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','ratified')),
  visibility TEXT NOT NULL DEFAULT 'org' CHECK (visibility IN ('org','private')),
  current_version INTEGER NOT NULL DEFAULT 0 CHECK (current_version >= 0),
  ratified_version INTEGER,
  ratified_by TEXT,                              -- a person handle
  ratified_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL, published_at TEXT, deleted_at TEXT, deleted_by TEXT,                      -- created_at of the LATEST version: the library's sort key
  CHECK ((status = 'ratified') = (ratified_version IS NOT NULL AND ratified_by IS NOT NULL AND ratified_at IS NOT NULL)),
  CHECK (status = 'ratified' OR (ratified_version IS NULL AND ratified_by IS NULL AND ratified_at IS NULL))
);
INSERT INTO artifact_pages_old (id, slug, title, kind, area, repo, author_id, status, visibility, current_version, ratified_version, ratified_by, ratified_at, created_at, updated_at, published_at, deleted_at, deleted_by) SELECT id, slug, title, kind, area, repo, author_id, status, visibility, current_version, ratified_version, ratified_by, ratified_at, created_at, updated_at, published_at, deleted_at, deleted_by FROM artifact_pages WHERE org_id = 'org_saplinglearn';
INSERT INTO sqlite_sequence (name, seq) SELECT 'artifact_pages_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'artifact_pages_old');
UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = 'artifact_pages'), 0)) WHERE name = 'artifact_pages_old';
CREATE TABLE doc_images_old (
  sha256 TEXT PRIMARY KEY CHECK (length(sha256) = 64),
  content_type TEXT NOT NULL CHECK (content_type IN ('image/png','image/jpeg','image/gif','image/webp')),
  size_bytes INTEGER NOT NULL CHECK (size_bytes >= 1 AND size_bytes <= 10485760),
  uploaded_by TEXT NOT NULL,                     -- a person handle
  created_at TEXT NOT NULL
);
INSERT INTO doc_images_old (sha256, content_type, size_bytes, uploaded_by, created_at) SELECT sha256, content_type, size_bytes, uploaded_by, created_at FROM doc_images WHERE org_id = 'org_saplinglearn';
DROP TABLE doc_versions;
DROP TABLE pr_summaries;
DROP TABLE prompt_versions;
DROP TABLE docs;
DROP TABLE entry_tags;
DROP TABLE processed_items;
DROP TABLE events;
DROP TABLE issue_summaries;
DROP TABLE plan;
DROP TABLE plan_versions;
DROP TABLE identity_tasks;
DROP TABLE notification_policy;
DROP TABLE notification_settings;
DROP TABLE notification_prefs;
DROP TABLE repo_events;
DROP TABLE repo_snapshots;
DROP TABLE repo_metrics;
DROP TABLE prompts;
DROP TABLE artifact_pages;
DROP TABLE doc_images;
ALTER TABLE docs_old RENAME TO docs;
ALTER TABLE doc_versions_old RENAME TO doc_versions;
ALTER TABLE entry_tags_old RENAME TO entry_tags;
ALTER TABLE processed_items_old RENAME TO processed_items;
ALTER TABLE events_old RENAME TO events;
ALTER TABLE pr_summaries_old RENAME TO pr_summaries;
ALTER TABLE issue_summaries_old RENAME TO issue_summaries;
ALTER TABLE plan_old RENAME TO plan;
ALTER TABLE plan_versions_old RENAME TO plan_versions;
ALTER TABLE identity_tasks_old RENAME TO identity_tasks;
ALTER TABLE notification_policy_old RENAME TO notification_policy;
ALTER TABLE notification_settings_old RENAME TO notification_settings;
ALTER TABLE notification_prefs_old RENAME TO notification_prefs;
ALTER TABLE repo_events_old RENAME TO repo_events;
ALTER TABLE repo_snapshots_old RENAME TO repo_snapshots;
ALTER TABLE repo_metrics_old RENAME TO repo_metrics;
ALTER TABLE prompts_old RENAME TO prompts;
ALTER TABLE prompt_versions_old RENAME TO prompt_versions;
ALTER TABLE artifact_pages_old RENAME TO artifact_pages;
ALTER TABLE doc_images_old RENAME TO doc_images;
CREATE INDEX idx_artifact_pages_author ON artifact_pages(author_id);
CREATE INDEX idx_artifact_pages_updated ON artifact_pages(updated_at);
CREATE INDEX idx_doc_versions_hash ON doc_versions(slug, content_hash);
CREATE INDEX idx_doc_versions_slug ON doc_versions(slug);
CREATE INDEX idx_docs_space ON docs(space, section);
CREATE INDEX idx_entry_tags_lookup ON entry_tags(entry_type, entry_id);
CREATE INDEX idx_events_ref ON events(event_type, ref_number, occurred_at);
CREATE INDEX idx_events_subject ON events(event_type, subject_login, occurred_at);
CREATE INDEX idx_repo_events_deploys ON repo_events(kind, env, part, occurred_at);
CREATE INDEX idx_repo_events_kind_at ON repo_events(kind, occurred_at);
CREATE INDEX idx_repo_events_kind_number ON repo_events(kind, number, occurred_at);
CREATE INDEX idx_repo_events_kind_ref ON repo_events(kind, ref, occurred_at);
CREATE INDEX idx_repo_events_kind_sha ON repo_events(kind, sha);
CREATE INDEX idx_repo_metrics_series ON repo_metrics(metric, env, part, at);

-- ── 5. the org tables and the two person/identity columns ──
DROP TABLE IF EXISTS org_audit;
DROP TABLE IF EXISTS org_secrets;
DROP TABLE IF EXISTS org_keys;
DROP TABLE IF EXISTS org_integration_config;
DROP TABLE IF EXISTS org_environments;
DROP TABLE IF EXISTS org_repos;
DROP TABLE IF EXISTS org_login_map;
DROP TABLE IF EXISTS org_invites;
DROP TABLE IF EXISTS memberships;
DROP TABLE IF EXISTS org_counters;
DROP TABLE IF EXISTS cron_cursor;
DROP TABLE IF EXISTS orgs;
ALTER TABLE persons DROP COLUMN org_limit;
ALTER TABLE identities DROP COLUMN verified_email;

-- ── 6. FTS: the 0036 tables and triggers, re-populated ──
CREATE TABLE _mt_artifacts_fts_hold (page_id TEXT, title TEXT, description TEXT, body TEXT);
INSERT INTO _mt_artifacts_fts_hold SELECT page_id, title, description, body FROM artifacts_fts;
DROP TABLE IF EXISTS docs_fts;
DROP TABLE IF EXISTS feed_fts;
DROP TABLE IF EXISTS adrs_fts;
DROP TABLE IF EXISTS roadmap_fts;
DROP TABLE IF EXISTS tickets_fts;
DROP TABLE IF EXISTS prompts_fts;
DROP TABLE IF EXISTS artifacts_fts;
CREATE VIRTUAL TABLE docs_fts USING fts5(
  slug UNINDEXED, title, section UNINDEXED, body, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE feed_fts USING fts5(
  feed_id UNINDEXED, summary, body, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE adrs_fts USING fts5(
  adr_id UNINDEXED, title, context, decision, rationale, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE roadmap_fts USING fts5(
  ref UNINDEXED, title, body, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE tickets_fts USING fts5(
  ticket_id UNINDEXED, title, body, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE prompts_fts USING fts5(
  slug, title, description, body, tags, tokenize = 'porter unicode61');
CREATE VIRTUAL TABLE artifacts_fts USING fts5(
  page_id UNINDEXED, title, description, body, tokenize = 'porter unicode61');
CREATE TRIGGER adrs_fts_ad AFTER DELETE ON adrs BEGIN
  DELETE FROM adrs_fts WHERE adr_id = CAST(old.id AS TEXT);
END;
CREATE TRIGGER adrs_fts_ai AFTER INSERT ON adrs BEGIN
  INSERT INTO adrs_fts (adr_id, title, context, decision, rationale)
    VALUES (CAST(new.id AS TEXT), new.title, new.context, new.decision, new.rationale);
END;
CREATE TRIGGER artifacts_fts_ad AFTER DELETE ON artifact_pages BEGIN
  DELETE FROM artifacts_fts WHERE page_id = CAST(old.id AS TEXT);
END;
CREATE TRIGGER docs_fts_ad AFTER DELETE ON docs BEGIN
  DELETE FROM docs_fts WHERE slug = old.slug;
END;
CREATE TRIGGER docs_fts_ai AFTER INSERT ON docs BEGIN
  DELETE FROM docs_fts WHERE slug = new.slug;
  INSERT INTO docs_fts (slug, title, section, body)
    VALUES (new.slug, new.title, new.section, new.body);
END;
CREATE TRIGGER docs_fts_au AFTER UPDATE OF title, section, body ON docs BEGIN
  DELETE FROM docs_fts WHERE slug = new.slug;
  INSERT INTO docs_fts (slug, title, section, body)
    VALUES (new.slug, new.title, new.section, new.body);
END;
CREATE TRIGGER feed_fts_ad AFTER DELETE ON feed BEGIN
  DELETE FROM feed_fts WHERE feed_id = CAST(old.id AS TEXT);
END;
CREATE TRIGGER feed_fts_ai AFTER INSERT ON feed BEGIN
  INSERT INTO feed_fts (feed_id, summary, body)
    VALUES (CAST(new.id AS TEXT), new.summary, new.body);
END;
CREATE TRIGGER prompts_fts_ad AFTER DELETE ON prompts BEGIN
  DELETE FROM prompts_fts WHERE slug = old.slug;
END;
CREATE TRIGGER prompts_fts_ai AFTER INSERT ON prompts BEGIN
  DELETE FROM prompts_fts WHERE slug = new.slug;
  INSERT INTO prompts_fts (slug, title, description, body, tags)
    SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags
    FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version
    WHERE p.slug = new.slug AND p.deleted_at IS NULL;
END;
CREATE TRIGGER prompts_fts_au AFTER UPDATE OF slug, title, description, tags, current_version, deleted_at ON prompts BEGIN
  DELETE FROM prompts_fts WHERE slug = old.slug;
  DELETE FROM prompts_fts WHERE slug = new.slug;
  INSERT INTO prompts_fts (slug, title, description, body, tags)
    SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags
    FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version
    WHERE p.slug = new.slug AND p.deleted_at IS NULL;
END;
CREATE TRIGGER prompts_fts_vai AFTER INSERT ON prompt_versions BEGIN
  DELETE FROM prompts_fts WHERE slug = new.slug;
  INSERT INTO prompts_fts (slug, title, description, body, tags)
    SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags
    FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version
    WHERE p.slug = new.slug AND p.deleted_at IS NULL;
END;
CREATE TRIGGER prompts_fts_vau AFTER UPDATE ON prompt_versions BEGIN
  DELETE FROM prompts_fts WHERE slug = new.slug;
  INSERT INTO prompts_fts (slug, title, description, body, tags)
    SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags
    FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version
    WHERE p.slug = new.slug AND p.deleted_at IS NULL;
END;
CREATE TRIGGER roadmap_fts_plan_au AFTER UPDATE OF narrative ON plan BEGIN
  DELETE FROM roadmap_fts WHERE ref = 'plan';
  INSERT INTO roadmap_fts (ref, title, body)
    SELECT 'plan', 'Roadmap plan', new.narrative WHERE new.narrative != '';
END;
CREATE TRIGGER roadmap_fts_sprint_ad AFTER DELETE ON sprints BEGIN
  DELETE FROM roadmap_fts WHERE ref = 'sprint:' || old.id;
END;
CREATE TRIGGER roadmap_fts_sprint_ai AFTER INSERT ON sprints BEGIN
  DELETE FROM roadmap_fts WHERE ref = 'sprint:' || new.id;
  INSERT INTO roadmap_fts (ref, title, body)
    VALUES ('sprint:' || new.id, new.title,
            COALESCE(new.description, '') || ' ' || COALESCE(new.summary, '') || ' ' ||
            COALESCE(new.phase, '') || ' ' || COALESCE(new.status, ''));
END;
CREATE TRIGGER roadmap_fts_sprint_au AFTER UPDATE OF title, description, summary, phase, status ON sprints BEGIN
  DELETE FROM roadmap_fts WHERE ref = 'sprint:' || new.id;
  INSERT INTO roadmap_fts (ref, title, body)
    VALUES ('sprint:' || new.id, new.title,
            COALESCE(new.description, '') || ' ' || COALESCE(new.summary, '') || ' ' ||
            COALESCE(new.phase, '') || ' ' || COALESCE(new.status, ''));
END;
CREATE TRIGGER tickets_fts_ad AFTER DELETE ON tickets BEGIN
  DELETE FROM tickets_fts WHERE ticket_id = CAST(old.id AS TEXT);
END;
CREATE TRIGGER tickets_fts_ai AFTER INSERT ON tickets BEGIN
  DELETE FROM tickets_fts WHERE ticket_id = CAST(new.id AS TEXT);
  INSERT INTO tickets_fts (ticket_id, title, body)
    VALUES (CAST(new.id AS TEXT), new.title, new.body);
END;
CREATE TRIGGER tickets_fts_au AFTER UPDATE OF title, body ON tickets BEGIN
  DELETE FROM tickets_fts WHERE ticket_id = CAST(new.id AS TEXT);
  INSERT INTO tickets_fts (ticket_id, title, body)
    VALUES (CAST(new.id AS TEXT), new.title, new.body);
END;
INSERT INTO docs_fts (slug, title, section, body) SELECT slug, title, section, body FROM docs;
INSERT INTO feed_fts (feed_id, summary, body) SELECT CAST(id AS TEXT), summary, body FROM feed;
INSERT INTO adrs_fts (adr_id, title, context, decision, rationale) SELECT CAST(id AS TEXT), title, context, decision, rationale FROM adrs;
INSERT INTO roadmap_fts (ref, title, body) SELECT 'plan', 'Roadmap plan', narrative FROM plan WHERE narrative != '';
INSERT INTO roadmap_fts (ref, title, body) SELECT 'sprint:' || id, title, COALESCE(description, '') || ' ' || COALESCE(summary, '') || ' ' || COALESCE(phase, '') || ' ' || COALESCE(status, '') FROM sprints;
INSERT INTO tickets_fts (ticket_id, title, body) SELECT CAST(id AS TEXT), title, body FROM tickets;
INSERT INTO prompts_fts (slug, title, description, body, tags) SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version WHERE p.deleted_at IS NULL;
INSERT INTO artifacts_fts (page_id, title, description, body) SELECT page_id, title, description, body FROM _mt_artifacts_fts_hold;
DROP TABLE _mt_artifacts_fts_hold;

-- ── 7. guard, ledger ──
CREATE TABLE _mt_fk_guard (violations INTEGER NOT NULL CHECK (violations = 0));
INSERT INTO _mt_fk_guard (violations) SELECT COUNT(*) FROM pragma_foreign_key_check;
DROP TABLE _mt_fk_guard;
-- Forgotten, so a later `migrations apply` runs the migration again from the top.
DELETE FROM d1_migrations WHERE name = '0042_organizations.sql';

PRAGMA defer_foreign_keys = false;
