#!/usr/bin/env python3
"""Generate scripts/mt/rollback/0042_organizations.down.sql — the forward-fix rollback of
migrations/0042_organizations.sql (canopy-multitenancy.md §3.5). It is GENERATED from the real 0036 schema
(migrations 0001–0036 applied to a scratch SQLite; 0041 changes data only), so every restored table,
index, FTS table and trigger is byte-for-byte the 0036 definition. Re-run after editing the migration:
python3 scripts/mt/build-rollback.py   (CI fails when the committed file is stale)
"""
import glob, os, re, sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LEGACY = "org_saplinglearn"
REBUILT = ["docs", "doc_versions", "entry_tags", "processed_items", "events", "pr_summaries", "issue_summaries",
           "plan", "plan_versions", "identity_tasks", "notification_policy", "notification_settings",
           "notification_prefs", "repo_events", "repo_snapshots", "repo_metrics", "prompts", "prompt_versions",
           "artifact_pages", "doc_images"]
ADDED_COLUMN = ["feed", "adrs", "needs_triage", "sprints", "sprint_resources", "sprint_progress", "tickets",
                "ticket_assignees", "ticket_links", "ticket_comments", "ticket_events", "handoffs", "mcp_tokens",
                "oauth_grants", "oauth_codes", "artifact_versions", "artifact_links", "artifact_upload_tokens",
                "doc_image_upload_tokens", "notification_outbox", "notification_outbox_bodies"]
PLATFORM = ["org_audit", "org_secrets", "org_keys", "org_integration_config", "org_environments", "org_repos",
            "org_login_map", "org_invites", "memberships", "org_counters", "cron_cursor", "orgs"]
FTS = ["docs_fts", "feed_fts", "adrs_fts", "roadmap_fts", "tickets_fts", "prompts_fts", "artifacts_fts"]
# Sections 5–8 of the migration: free-standing tables (dropped) and the one column added to `identities`.
LATER_TABLES = ["abuse_counters", "org_admin_audit", "org_usage_daily", "platform_admins"]
UP_FILE = "0042_organizations.sql"
DOWN_FILE = "0042_organizations.down.sql"

db = sqlite3.connect(":memory:", isolation_level=None)
for f in sorted(glob.glob(os.path.join(ROOT, "migrations", "*.sql"))):
    if os.path.basename(f) > "0036_person_profiles.sql":  # 0041 (a data change) and the migration itself
        break
    db.executescript("BEGIN;" + open(f).read() + ";COMMIT;")

def sql_of(name):
    return db.execute("SELECT sql FROM sqlite_master WHERE name = ?", (name,)).fetchone()[0]

def cols(table):
    return [r[1] for r in db.execute(f"PRAGMA table_info({table})")]

def autoinc(table):
    return "AUTOINCREMENT" in sql_of(table).upper()

out = []
w = out.append
w("-- GENERATED by scripts/mt/build-rollback.py — do not edit by hand.")
w("-- Rollback of migrations/0042_organizations.sql — ALL of it — to the exact schema the database had before")
w("-- it: 0036, with 0041 applied (canopy-multitenancy.md §3.5). What was added last is undone first:")
w("-- sections 10–5 (the org's image, the invite's mail columns, the abuse counters, the identity uid, the")
w("-- platform tables, the superadmin), then 4–1 (search, the rebuilt tables, the added columns, the org")
w("-- tables). ONE transaction: it either completes or changes nothing.")
w("--")
w("-- NOT undone:")
w("--   • 0041_trov_name.sql — its own migration, applied before this one: the default sender stays")
w("--     `Trov <hello@trov.dev>` and 0041 stays recorded in d1_migrations.")
w("--   • nothing else. Unlike a rollback of ten separate files, no added column may be left behind, however")
w("--     harmless (`identities.provider_uid`, `persons.org_limit`, …): this file also removes the migration")
w("--     from d1_migrations, and the next `migrations apply` would fail on a column that still exists.")
w("-- LOST with it (there is nowhere in the old schema to keep them): every org, membership, invite,")
w("-- repository / environment row, integration secret and audit row; usage and abuse counters; the GitHub")
w("-- account ids pinned at sign-in (re-pinned at the next one); org images' columns (the bytes stay in R2).")
w(f"-- It keeps ONLY the '{LEGACY}' rows of every tenant table, so it REFUSES to run once any other org")
w("-- exists (the guard below) — and on a database the migration never ran on (there is no `orgs`). Apply with")
w(f"--   wrangler d1 execute trov --remote --file scripts/mt/rollback/{DOWN_FILE}")
w("-- together with `wrangler rollback` to the pre-migration Worker. Prefer D1 Time Travel when in its window.")
w("")
w("PRAGMA defer_foreign_keys = true;")
w("")
w("-- Refuse when another org exists: its rows would be deleted.")
w("CREATE TABLE _mt_down_guard (other_orgs INTEGER NOT NULL CHECK (other_orgs = 0));")
w(f"INSERT INTO _mt_down_guard (other_orgs) SELECT COUNT(*) FROM orgs WHERE id <> '{LEGACY}';")
w("DROP TABLE _mt_down_guard;")
w("")
w("-- ── 1. sections 10–5: the later additions ──")
w("-- (Sections 10, 9 and 6's columns sit on `orgs` / `org_invites`, which step 5 drops whole.)")
w("DROP INDEX IF EXISTS idx_abuse_counters_bucket;")
w("DROP INDEX IF EXISTS idx_org_admin_audit_org;")
w("DROP INDEX IF EXISTS idx_org_admin_audit_at;")
w("DROP INDEX IF EXISTS idx_org_usage_daily_day;")
for t in LATER_TABLES:
    w(f"DROP TABLE IF EXISTS {t};")
w("ALTER TABLE identities DROP COLUMN provider_uid;")
w("")
w("-- ── 2. every trigger the migration created (they reference org_id) ──")
for t in ["docs_fts_ai", "docs_fts_au", "docs_fts_ad", "feed_fts_ai", "feed_fts_ad", "adrs_fts_ai", "adrs_fts_ad",
          "roadmap_fts_plan_au", "roadmap_fts_sprint_ai", "roadmap_fts_sprint_au", "roadmap_fts_sprint_ad",
          "tickets_fts_ai", "tickets_fts_au", "tickets_fts_ad", "prompts_fts_ai", "prompts_fts_au", "prompts_fts_ad",
          "prompts_fts_vai", "prompts_fts_vau", "artifacts_fts_ad", "tickets_number_ai", "handoffs_number_ai"]:
    w(f"DROP TRIGGER IF EXISTS {t};")
w("")
w("-- ── 3. the tables that only GAINED org_id (and number): drop the indexes on it, then the columns ──")
for i in ["idx_sprints_org_id", "idx_tickets_org_id", "idx_tickets_source_ref", "idx_tickets_org_number",
          "idx_handoffs_org_number", "idx_adrs_hash_org"]:
    w(f"DROP INDEX IF EXISTS {i};")
for t in ADDED_COLUMN:
    w(f"DELETE FROM {t} WHERE org_id <> '{LEGACY}';")
for t in ADDED_COLUMN:
    w(f"ALTER TABLE {t} DROP COLUMN org_id;")
w("ALTER TABLE tickets DROP COLUMN number;")
w("ALTER TABLE handoffs DROP COLUMN number;")
w(sql_of("idx_tickets_source_ref") + ";")
w("")
w("-- ── 4. the rebuilt tables, back to their 0036 definitions ──")
for t in REBUILT:
    create = sql_of(t)
    create = re.sub(r'^CREATE TABLE\s+"?' + re.escape(t) + r'"?', f"CREATE TABLE {t}_old", create)
    for parent in REBUILT:
        create = re.sub(r'REFERENCES\s+"?' + re.escape(parent) + r'"?\s*\(', f"REFERENCES {parent}_old(", create)
    w(create + ";")
    c = cols(t)
    if t in ("plan", "notification_settings"):
        sel = ", ".join("1" if x == "id" else x for x in c)
    else:
        sel = ", ".join(c)
    w(f"INSERT INTO {t}_old ({', '.join(c)}) SELECT {sel} FROM {t} WHERE org_id = '{LEGACY}';")
    if autoinc(t):
        w(f"INSERT INTO sqlite_sequence (name, seq) SELECT '{t}_old', 0 WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = '{t}_old');")
        w(f"UPDATE sqlite_sequence SET seq = MAX(seq, COALESCE((SELECT seq FROM sqlite_sequence WHERE name = '{t}'), 0)) WHERE name = '{t}_old';")
# children before parents
for t in ["doc_versions", "pr_summaries", "prompt_versions"] + [x for x in REBUILT if x not in ("doc_versions", "pr_summaries", "prompt_versions")]:
    w(f"DROP TABLE {t};")
for t in REBUILT:
    w(f"ALTER TABLE {t}_old RENAME TO {t};")
for (name, sql) in db.execute("SELECT name, sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL ORDER BY name"):
    tbl = db.execute("SELECT tbl_name FROM sqlite_master WHERE name = ?", (name,)).fetchone()[0]
    if tbl in REBUILT:
        w(sql + ";")
w("")
w("-- ── 5. the org tables and the two person/identity columns ──")
for t in PLATFORM:
    w(f"DROP TABLE IF EXISTS {t};")
w("ALTER TABLE persons DROP COLUMN org_limit;")
w("ALTER TABLE identities DROP COLUMN verified_email;")
w("")
w("-- ── 6. FTS: the 0036 tables and triggers, re-populated ──")
w("CREATE TABLE _mt_artifacts_fts_hold (page_id TEXT, title TEXT, description TEXT, body TEXT);")
w("INSERT INTO _mt_artifacts_fts_hold SELECT page_id, title, description, body FROM artifacts_fts;")
for t in FTS:
    w(f"DROP TABLE IF EXISTS {t};")
for t in FTS:
    w(sql_of(t) + ";")
for (name, sql) in db.execute("SELECT name, sql FROM sqlite_master WHERE type = 'trigger' ORDER BY name"):
    w(sql + ";")
w("INSERT INTO docs_fts (slug, title, section, body) SELECT slug, title, section, body FROM docs;")
w("INSERT INTO feed_fts (feed_id, summary, body) SELECT CAST(id AS TEXT), summary, body FROM feed;")
w("INSERT INTO adrs_fts (adr_id, title, context, decision, rationale) SELECT CAST(id AS TEXT), title, context, decision, rationale FROM adrs;")
w("INSERT INTO roadmap_fts (ref, title, body) SELECT 'plan', 'Roadmap plan', narrative FROM plan WHERE narrative != '';")
w("INSERT INTO roadmap_fts (ref, title, body) SELECT 'sprint:' || id, title, COALESCE(description, '') || ' ' || COALESCE(summary, '') || ' ' || COALESCE(phase, '') || ' ' || COALESCE(status, '') FROM sprints;")
w("INSERT INTO tickets_fts (ticket_id, title, body) SELECT CAST(id AS TEXT), title, body FROM tickets;")
w("INSERT INTO prompts_fts (slug, title, description, body, tags) SELECT p.slug, p.title, p.description, COALESCE(v.body, ''), p.tags FROM prompts p LEFT JOIN prompt_versions v ON v.slug = p.slug AND v.version = p.current_version WHERE p.deleted_at IS NULL;")
w("INSERT INTO artifacts_fts (page_id, title, description, body) SELECT page_id, title, description, body FROM _mt_artifacts_fts_hold;")
w("DROP TABLE _mt_artifacts_fts_hold;")
w("")
w("-- ── 7. guard, ledger ──")
w("CREATE TABLE _mt_fk_guard (violations INTEGER NOT NULL CHECK (violations = 0));")
w("INSERT INTO _mt_fk_guard (violations) SELECT COUNT(*) FROM pragma_foreign_key_check;")
w("DROP TABLE _mt_fk_guard;")
w("-- Forgotten, so a later `migrations apply` runs the migration again from the top.")
w(f"DELETE FROM d1_migrations WHERE name = '{UP_FILE}';")
w("")
w("PRAGMA defer_foreign_keys = false;")
open(os.path.join(ROOT, "scripts", "mt", "rollback", DOWN_FILE), "w").write("\n".join(out) + "\n")
print("wrote", len(out), "lines")
